[default.tls]
key = "../certs/mkn.edu.key"   # Path or bytes to DER-encoded ASN.1 PKCS#1/#8 or SEC1 key.
certs = "../certs/mkn.edu.crt"
serve_on = ["https"]

[default]
address = "127.0.0.1"
port = 8080
