services:
  server:
    build:
      context: ./server
    container_name: backend
    stop_grace_period: 1s
    image: kirillog/chat-app:server

  client:
    build:
      context: ./client
    container_name: frontend
    image: kirillog/chat-app:client
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: kirillog/chat-app:nginx
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=kirill.mitkin.03@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      - client

volumes:
  nginx_secrets: