version: '3.8'

services:
  server:
    build:
      context: ./server
    container_name: backend
    stop_grace_period: 1s
    image: kirillog/chat-app:server

  client:
    build:
      context: ./client
    container_name: frontend
    image: kirillog/chat-app:client
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: kirillog/chat-app:nginx
    ports:
      - "443:443"
    depends_on:
      - client
