version: '3.8'

services:
  server:
    build:
      context: ./server
    container_name: backend
    stop_grace_period: 1s

  client:
    build:
      context: ./client
    container_name: frontend
    depends_on:
      - server

  nginx:
    image: nginx:1-alpine
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - client
    volumes:
      - /home/kirill/Univer/Web/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-log:/var/log/nginx/
